services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: hypercorn bot:quart_app --bind 0.0.0.0:10000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11